import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const customFontSans = 'font-[family-name:var(--font-geist-sans)]'
  const customFontMono = 'font-[family-name:var(--font-geist-mono)]'
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <div className={`min-h-screen 2xl:mx-96 sm:mx-40 sm:gap-16 ${customFontMono} bg-white rounded`}>
          <Header/>
            <main className="flex flex-col gap-8 items-center justify-center px-20 py-10">
          {children}
          </main>
        </div>
      </body>
    </html>
  );
}
